server:
  port: 0
spring:
  cache:
    type: caffeine
  application:
    name: userService
  ## MongoDB Properties
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user
      port: 27017
      host: mongodb
      auto-index-creation: true
  ## Zipkin and Sleuth Properties
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

## Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# JWT properties
jwt:
  secret:
    key: secret_secret_secret_secret_secret_secret_secret_secret_secret_secret